export const BUILDING_DESCRIPTIONS: Record<string, string> = {
  smallIndigoPlant: 'Produkuje 1 indygo za każdy aktywny slot. Wymaga aktywnej plantacji indygo.',
  largeIndigoPlant: 'Produkuje do 3 indygo (1 za każdy robotnik). Wymaga aktywnych plantacji indygo.',
  smallSugarMill: 'Produkuje 1 cukier za każdy aktywny slot. Wymaga aktywnej plantacji trzciny.',
  largeSugarMill: 'Produkuje do 3 cukru (1 za każdy robotnik). Wymaga aktywnych plantacji trzciny.',
  tobaccoStorage: 'Produkuje do 3 tytoniu (1 za każdy robotnik). Wymaga aktywnych plantacji tytoniu.',
  coffeeRoaster: 'Produkuje do 2 kawy (1 za każdy robotnik). Wymaga aktywnych plantacji kawy.',
  smallMarket: '+1 dublon przy każdej sprzedaży na targowisku.',
  smithy: 'Pozwala brać kamieniołom w fazie plantatora (przywilej plantatora bez bycia selektorem). Daje +1 zniżkę z kamieniołomu przy budowaniu ponad limit grupy cenowej.',
  hacienda: 'W fazie plantatora: po wzięciu plantacji losuj jeszcze jedną z zakrytego stosu.',
  hospice: 'Gdy bierzesz plantację lub kamieniołom, natychmiast kładź na niej robotnika z puli globalnej.',
  smallWarehouse: 'Po fazie kapitana możesz zachować pełny zapas 1 wybranego rodzaju towaru (zamiast odrzucać).',
  office: 'Możesz sprzedać na targowisku towar, który już tam leży (normalnie zabronione).',
  largeMarket: '+2 dublony przy każdej sprzedaży na targowisku.',
  largeWarehouse: 'Po fazie kapitana możesz zachować pełny zapas 2 wybranych rodzajów towaru.',
  factory: 'Po produkcji: za 2 różne rodzaje towarów +1 dublon, za 3 +2, za 4 +3, za 5 +5 dublonów.',
  university: 'Gdy zbudujesz budynek, natychmiast kładziony jest na nim robotnik z puli globalnej.',
  harbour: '+1 punkt zwycięstwa za każdy załadunek na statek w fazie kapitana.',
  wharf: 'Własny prywatny statek o nieograniczonej pojemności. Towary na tym statku nie są dzielone z innymi.',
  fortress: 'Koniec gry: +1 PZ za każdych 3 robotników (aktywnych i nieaktywnych) na twojej wyspie.',
  guildHall: 'Koniec gry: +1 PZ za każdy mały budynek produkcyjny, +2 PZ za każdy duży budynek produkcyjny.',
  customsHouse: 'Koniec gry: +1 PZ za każde 4 posiadane żetony PZ.',
  cityHall: 'Koniec gry: +1 PZ za każdy budynek użytkowy (mały i duży).',
  residence: 'Koniec gry: za 9 zajętych pól wiejskich +4 PZ, za 10 → +5, za 11 → +6, za 12 → +7 PZ.',
};
