# Osobny projekt Cloudflare Pages dla Puerto Rico.
name = "puerto-rico-3rd-edition"
account_id = "d75a5e5ada1cb7d25763bf96ea753e68"
pages_build_output_dir = "dist-pages"
compatibility_date = "2026-09-09"

[[d1_databases]]
binding = "STATS_DB"
database_name = "puerto-rico-match-statistics"
database_id = "8759c66a-f0a2-402e-9e85-b39613e942c0"
